config/routes.rb
Rails.application.routes.draw do
   devise_for :users

  get '/watch/:id', to: 'users#watch', as: :watch
  get '/stream', to: 'users#stream', as: :stream

  root 'users#stream'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stream.rb
class Stream < ApplicationRecord
   before_create do |stream|
    session = OpenTokClient.create_session
    print session
    stream.tokbox_session_id = session.session_id
  end

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_one :stream
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def stream
    @stream     = current_user.stream || current_user.create_stream
    gon.opentok = opentok_data(@stream)
  end

  def watch
    @stream = User.find(params[:id]).stream
    gon.opentok = opentok_data(@stream)
  end

  private

  def opentok_data(stream)
    token = OpenTokClient.generate_token(stream.tokbox_session_id)
    { sessionId: stream.tokbox_session_id, apiKey: Figaro.env.opentok_api_key, token: token }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title VideoCall
    = Gon::Base.render_data
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/users/stream.html.haml
= javascript_include_tag "https://static.opentok.com/v2/js/TB.min.js"
%h1 Your stream
#publisher
Link to your stream: 
= link_to watch_url(@stream.user.id), watch_url(@stream.user.id)

app/views/users/watch.html.haml
= javascript_include_tag  "https://static.opentok.com/v2/js/TB.min.js"
%h1
	= @stream.user.email
	's stream
#stream